---
# environment Name
oah_env_name: oah-vm
# `vagrant_box` .
#vagrant_box: "ubuntu/xenial64"
vagrant_box: "bento/ubuntu-16.04"
vagrant_user: vagrant
oah_env_user: vagrant
oah_user: oahdev

# If you need to run multiple instances of Openhack VM, set a unique hostname,
# machine name, and IP address for each instance.
vagrant_hostname: oah-vm.dev
vagrant_machine_name: oah-vm
#vagrant_ip: 192.168.88.88
vagrant_ip: 0.0.0.0

# Allow OAH VM to be accessed via a public network interface on your host.
# Vagrant boxes are insecure by default, so be careful. You've been warned!
# See: https://docs.vagrantup.com/v2/networking/public_network.html
vagrant_public_ip: ""
vagrant_gui: false
vagrant_synced_folder_default_type: nfs
# A list of synced folders, with the keys 'local_path', 'destination', 'id', and
# a 'type' of [nfs|rsync|smb] (leave empty for slow native shares).
vagrant_synced_folders: []
  # # TODO: The first synced folder will be used for the default oah installation.
  # - local_path: {{ oah_dir }}/.oah/data
  #   destination: /home/{{ oah_env_user }}/.oah/data
  #   type: nfs
  #   create: true

  # - local_path: ~/oah-sites/{{ vagrant_machine_name }}
  #   destination: /var/www/{{ vagrant_machine_name }}
  #   type: nfs
  #   create: true

# Memory and CPU to use for this VM.
vagrant_memory: 1024
vagrant_cpus: 2

vagrant_plugins:
  - name: vagrant-vbguest
  - name: vagrant-hostsupdater

# Minimum required versions.
oah_vagrant_version_min: '1.8.6'
oah_ansible_version_min: '2.2'
# Force use of ansible_local provisioner, even if Ansible is installed on host.
force_ansible_local: false
  
# # The web server software to use. Can be either 'apache' or 'nginx'.
# oahvm_webserver: apache

# Cron jobs are added to the root user's crontab. Keys include name (required),
# minute, hour, day, weekday, month, job (required), and state.
oahvm_cron_jobs: []
